# Setting host
- hosts: localhost
  gather_facts: false
#Variables
  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    image_name: my-ruby-app 
    image_tag: latest
    replicas: 2
# Pre-Tasks to check if Minikube is running and start if not running
  pre_tasks:
    - name: Check Minikube's status.
      command: minikube status
      register: minikube_status
      changed_when: false
      ignore_errors: true
    # If minikube not started then start the same
    - name: Starting minikube as it is not running
      command: minikube start
      when: "not minikube_status.stdout or 'Running' not in minikube_status.stdout"
